lnd_user: "lnd"
lnd_dir: "/srv/payrank/lnd"
lnd_conf_dir: "{{lnd_dir}}/etc"
lnd_log_dir: "{{lnd_dir}}/log"
lnd_data_dir: "{{lnd_dir}}/data"
lnd_alias: "test"
lnd_bitcoin_node: "bitcoind"
node_external_ip: "1.1.1.1"
lnd_version: "v0.13.1-beta" 
lnd_arch: "arm64"
lnd_tar_name: "lnd-linux-{{lnd_arch}}-{{lnd_version}}"
lnd_tar: "{{lnd_tar_name}}.tar.gz"
lnd_url: "https://github.com/lightningnetwork/lnd/releases/download/{{lnd_version}}/{{lnd_tar}}"

lndconnect_user: "lnd"
lndconnect_version: "v0.2.0"
lndconnect_tar_name: "lndconnect-linux-{{lnd_arch}}-{{lndconnect_version}}"
lndconnect_tar: "{{lndconnect_tar_name}}.tar.gz"
lndconnect_url: "https://github.com/LN-Zap/lndconnect/releases/download/{{lndconnect_version}}/{{lndconnect_tar}}"
